living_room_thermostat_heat_default:
  automation:
    - alias: "Living Room - Thermostat - Heat - Default Reset"
      id: living_room_thermostat_heat_default_reset
      mode: single
      trigger:
        - platform: time_pattern
          hours: "*"
          minutes: "0"
          seconds: "0"
      action:
        - service: climate.set_temperature
          target:
            entity_id: climate.l
  input_number:
    living_room_thermostat_heat_default:
      name: Living Room Thermostat Heat Default
      min: 0
      max: 100
      mode: box
      step: 1
      unit_of_measurement: "°F"
