bedroom_thermostat_cool_default:
  automation:
    - alias: 'Bedroom - Thermostat - Cool - Default Reset'
      id: bedroom_thermostat_cool_default_reset
      trigger:
        - platform: time_pattern
          hours: '/4'
      action:
        - service: climate.set_temperature
          target:
            entity_id: climate.bedroom_thermostat_cool
          data:
            temperature: "{{ states('input_number.bedroom_thermostat_cool_default') | float }}"
  input_number:
    bedroom_thermostat_cool_default:
      name: Bedroom Thermostat Cool Default
      min: 0
      max: 100
      mode: box
      step: 1
      unit_of_measurement: '°F'
      icon: mdi:thermostat
