- id: '0'
  alias: Living Room - Lights - Evening
  trigger:
  - platform: state
    entity_id: sun.sun
    from: above_horizon
    to: below_horizon
  action:
  - service: light.turn_on
    data:
      transition: 30
      brightness_pct: 25
    target:
      device_id: 159ccd586ed56fe4105ec328db331bba
  mode: single
- id: '1622464029480'
  alias: Living Room - Lights - Night
  description: Turn off living room lights at night
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 30
      brightness: 1
    target:
      device_id: 159ccd586ed56fe4105ec328db331bba
  mode: single
- id: '1'
  alias: Bedroom - Fan - Hourly
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
    seconds: '0'
  condition:
  - condition: state
    entity_id: fan.bedroom_air_purifier
    state: 'on'
  - condition: time
    after: '10:00:00'
    before: '18:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: fan.set_percentage
    data:
      percentage: 66
    target:
      entity_id: fan.bedroom_air_purifier
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: fan.set_percentage
    data:
      percentage: 33
    target:
      entity_id: fan.bedroom_air_purifier
  mode: single
- id: '1623323556246'
  alias: Bedroom - Fan - Away
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.pixel_4
    zone: zone.home
    event: leave
  condition: []
  action:
  - service: fan.set_percentage
    target:
      entity_id: fan.bedroom_air_purifier
    data:
      percentage: 33
  mode: single
- id: '1624233736997'
  alias: Kitchen - Motion Sensor - Detected
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_81b0c306_ias_zone
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: adaptive_lighting.apply
    data:
      adapt_brightness: true
      adapt_color: true
      entity_id: switch.adaptive_lighting_kitchen
      lights: light.kitchen_lights
      transition: 30
      turn_on_lights: false
  - service: light.turn_on
    target:
      entity_id: light.kitchen_lights
    data:
      transition: 30
  mode: single
- id: '1624234430681'
  alias: Kitchen - Motion Sensor - Cleared
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_81b0c306_ias_zone
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: kitchen
    data:
      transition: 30
  mode: single
- id: '1624629970511'
  alias: Bedroom - Fan - Night
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - service: fan.set_preset_mode
    target:
      entity_id: fan.bedroom_air_purifier
    data:
      preset_mode: auto
  mode: single
- id: '1624826924089'
  alias: Storage Room - Motion Sensor - Detected
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_33b0c306_ias_zone
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: adaptive_lighting.apply
    data:
      adapt_brightness: true
      adapt_color: true
      entity_id: switch.adaptive_lighting_storage_room
      lights: light.storage_room_lights
      transition: 30
      turn_on_lights: false
  - service: light.turn_on
    target:
      entity_id: light.storage_room_lights
    data:
      transition: 30
  mode: single
- id: '1624826963295'
  alias: Storage Room - Motion Sensor - Cleared
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_33b0c306_ias_zone
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 30
    target:
      area_id: storage_room
  mode: single
- id: '1627403162160'
  alias: Location - Away - Air Conditioner
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.pixel_4
    zone: zone.tarrytown
    event: leave
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.harmony_hub_air_conditioner
  mode: single
- id: '1627403570362'
  alias: Location - Tarrytown - Air Conditioner
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.pixel_4
    zone: zone.tarrytown
    event: enter
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.harmony_hub_air_conditioner
  mode: single
- id: '1627917470477'
  alias: Nest Hub - Home Assistant
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.nest_hub
    to: idle
  condition: []
  action:
  - service: cast.show_lovelace_view
    data:
      entity_id: media_player.nest_hub
      view_path: '0'
      dashboard_path: lovelace
  mode: single
- id: '1627917861328'
  alias: Cast to Google Hub
  description: ''
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      dashboard: lovelace
      player: media_player.nest_hub
      view: lights
