- id: '0'
  alias: Living Room - Lights - Evening
  trigger:
  - platform: state
    entity_id: sun.sun
    from: above_horizon
    to: below_horizon
  action:
  - service: light.turn_on
    data:
      transition: 30
      brightness_pct: 25
    target:
      device_id: 159ccd586ed56fe4105ec328db331bba
  mode: single
- id: '1622464029480'
  alias: Living Room - Lights - Night
  description: Turn off living room lights at night
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 30
      brightness: 1
    target:
      device_id: 159ccd586ed56fe4105ec328db331bba
  mode: single
- id: '1'
  alias: Bedroom - Fan - Hourly
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
    seconds: '0'
  condition:
  - condition: state
    entity_id: fan.bedroom_air_purifier
    state: 'on'
  - condition: time
    after: '10:00:00'
    before: '18:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: fan.set_percentage
    data:
      percentage: 66
    target:
      entity_id: fan.bedroom_air_purifier
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: fan.set_preset_mode
    target:
      entity_id: fan.bedroom_air_purifier
    data:
      preset_mode: auto
  mode: single
- id: '1623323556246'
  alias: Bedroom - Fan - Away
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.pixel_4
    zone: zone.home
    event: leave
  condition: []
  action:
  - service: fan.set_percentage
    target:
      entity_id: fan.bedroom_air_purifier
    data:
      percentage: 33
  mode: single
- id: '1624233736997'
  alias: Kitchen - Motion Sensor - Detected
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_81b0c306_ias_zone
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: adaptive_lighting.apply
    data:
      adapt_brightness: true
      adapt_color: true
      entity_id: switch.adaptive_lighting_kitchen
      lights: light.kitchen_lights
      turn_on_lights: false
  - service: light.turn_on
    target:
      entity_id: light.kitchen_lights
    data:
      transition: 30
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: adaptive_lighting.apply
    data:
      adapt_brightness: true
      adapt_color: true
      entity_id: switch.adaptive_lighting_kitchen
      lights: light.kitchen_lights
      transition: 45
  mode: single
- id: '1624234430681'
  alias: Kitchen - Motion Sensor - Cleared
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_81b0c306_ias_zone
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: kitchen
    data:
      transition: 30
  mode: single
- id: '1624629970511'
  alias: Bedroom - Fan - Night
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - service: fan.set_preset_mode
    target:
      entity_id: fan.bedroom_air_purifier
    data:
      preset_mode: auto
  mode: single
- id: '1624826924089'
  alias: Storage Room - Motion Sensor - Detected
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_33b0c306_ias_zone
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: adaptive_lighting.apply
    data:
      adapt_brightness: true
      adapt_color: true
      entity_id: switch.adaptive_lighting_storage_room
      lights: light.storage_room_lights
      turn_on_lights: false
  - service: light.turn_on
    target:
      entity_id: light.storage_room_lights
    data:
      transition: 45
  mode: single
- id: '1624826963295'
  alias: Storage Room - Motion Sensor - Cleared
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_33b0c306_ias_zone
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 30
    target:
      area_id: storage_room
  mode: single
- id: '1627403162160'
  alias: Location - Away - Air Conditioner
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.pixel_4
    zone: zone.tarrytown
    event: leave
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.harmony_hub_air_conditioner
  mode: single
- id: '1627403570362'
  alias: Location - Tarrytown - Air Conditioner
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.pixel_4
    zone: zone.tarrytown
    event: enter
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.harmony_hub_air_conditioner
  mode: single
- id: '1629809644856'
  alias: Bedroom - Temperature - High
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.bedroom_temperature
    above: '80'
  condition: []
  action:
  - device_id: d1a44f8638db4133026efb806cdf894b
    domain: mobile_app
    type: notify
    title: ''
    message: Bedroom temperature is 80°
  - condition: zone
    entity_id: person.andrew_noblet
    zone: zone.home
  - service: switch.turn_on
    target:
      entity_id: switch.bedroom_air_conditioner
  mode: single
- id: '1629939843926'
  alias: Bedroom - Humidity - High
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.bedroom_humidity
    above: '50'
  condition: []
  action:
  - device_id: d1a44f8638db4133026efb806cdf894b
    domain: mobile_app
    type: notify
    title: ''
    message: The humidity is the bedroom is high. Turning off the humidifier.
  - service: switch.turn_off
    target:
      entity_id: switch.bedroom_humidifier
  mode: single
- id: '1629975317908'
  alias: Bedroom - Humidity - Low
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.bedroom_humidity
    below: '50'
  condition:
  - condition: zone
    entity_id: person.andrew_noblet
    zone: zone.tarrytown
  action:
  - device_id: d1a44f8638db4133026efb806cdf894b
    domain: mobile_app
    type: notify
    title: ''
    message: The humidity in the bedroom is low. Turning on the humidifier.
  - service: switch.turn_on
    target:
      entity_id: switch.bedroom_humidifier
  mode: single
- id: '1629986046617'
  alias: Living Room - Lights - Morning
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: living_room
  mode: single
- id: '1630087693865'
  alias: Bedroom - Weather - Temperature - Low
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.bedroom_weather_temperature_low
    to: 'on'
  condition: []
  action:
  - device_id: d1a44f8638db4133026efb806cdf894b
    domain: mobile_app
    type: notify
    title: ''
    message: It is colder outside than it is in your bedroom
  - service: switch.turn_off
    target:
      entity_id: switch.bedroom_air_conditioner
  mode: single
- id: '1630087918095'
  alias: Bedroom - Weather - Temperature - High
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.bedroom_weather_temperature_high
    to: 'on'
  condition: []
  action:
  - device_id: d1a44f8638db4133026efb806cdf894b
    domain: mobile_app
    type: notify
    title: ''
    message: It is warmer outside than it is in your bedroom
  - condition: zone
    entity_id: person.andrew_noblet
    zone: zone.tarrytown
  - service: switch.turn_on
    target:
      entity_id: switch.bedroom_air_conditioner
  mode: single
- id: '1630132249783'
  alias: Bedroom - Air Conditioner - Temperature - Low
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.bedroom_temperature
    to: '75'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.bedroom_air_conditioner
  mode: single
- id: '1630162886046'
  alias: Weather - Cool
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.openweathermap_feels_like_temperature
    below: '70'
  condition: []
  action:
  - device_id: d1a44f8638db4133026efb806cdf894b
    domain: mobile_app
    type: notify
    title: ''
    message: The temperature outside feels like it is < 70°. Consider opening up the
      windows.
  mode: single
- id: '1630162941846'
  alias: Weather - Hot
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.openweathermap_feels_like_temperature
    above: '70'
  condition: []
  action:
  - device_id: d1a44f8638db4133026efb806cdf894b
    domain: mobile_app
    type: notify
    title: ''
    message: The temperature outside feels like it is > 70°. Consider closing the
      windows.
  mode: single
- id: '1630358476326'
  alias: Bathroom - Motion Sensor - Detected
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion_ias
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: adaptive_lighting.apply
    data:
      adapt_brightness: true
      adapt_color: true
      entity_id: switch.adaptive_lighting_storage_room
      lights: light.storage_room_lights
      turn_on_lights: false
  - service: light.turn_on
    data:
      transition: 5
    target:
      area_id: bathroom
  mode: single
- id: '1630358731986'
  alias: Bathroom - Motion Sensor - Cleared
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion_ias
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 30
    target:
      area_id: bathroom
  mode: single
