- id: '0'
  alias: Living Room - Lights - Evening
  trigger:
  - platform: state
    entity_id: sun.sun
    from: above_horizon
    to: below_horizon
  action:
  - service: light.turn_on
    target:
      area_id: living_room
    data:
      transition: 30
      brightness_pct: 25
  mode: single
- id: '1622464029480'
  alias: Living Room - Lights - Night
  description: Turn off living room lights at night
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: living_room
    data:
      transition: 30
  mode: single
- id: '1'
  alias: Bedroom - Fan - Hourly
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
    seconds: '0'
  condition:
  - condition: time
    after: '10:00:00'
    before: '18:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: fan.set_percentage
    data:
      percentage: 66
    target:
      entity_id: fan.bedroom_air_purifier
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: fan.set_percentage
    data:
      percentage: 33
    target:
      entity_id: fan.bedroom_air_purifier
  mode: single
- id: '1623323556246'
  alias: Bedroom - Fan - Away
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.pixel_4
    zone: zone.home
    event: leave
  condition: []
  action:
  - service: fan.set_percentage
    target:
      entity_id: fan.bedroom_air_purifier
    data:
      percentage: 50
  mode: single
- id: '1623765646510'
  alias: Zone Notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.andrew_noblet
      zone_entity: zone.home
      notify_device: d1a44f8638db4133026efb806cdf894b
- id: '1624233736997'
  alias: Kitchen - Motion Sensor - Detected
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_81b0c306_ias_zone
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      area_id: kitchen
    data:
      transition: 30
  mode: single
- id: '1624234430681'
  alias: Kitchen - Motion Sensor - Cleared
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_81b0c306_ias_zone
    from: 'on'
    to: 'off'
    for: 00:02:00
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: kitchen
    data:
      transition: 30
  mode: single
