# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
scene: !include scenes.yaml

adaptive_lighting: !include_dir_list adaptive_lighting/

automation: !include automations.yaml

# device_tracker:
#   - platform: tplink_router
#     host: 192.168.0.1
#     username: !secret tplink_router_username
#     password: !secret tplink_router_password

frontend:
  themes: !include_dir_merge_named themes

google_assistant: !include google_assistant.yaml

homeassistant:
  external_url: https://anoblet.duckdns.org

http:
  base_url: https://anoblet.duckdns.org
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.200
    - 172.30.33.0/24
  cors_allowed_origins:
    - https://cast.home-assistant.io

light: !include_dir_list light/

logger:
  default: info
  logs: !include ./logger.yaml

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

media_player: !include media_player.yaml

recorder:
  commit_interval: 60
  db_url: !secret db_url

script: !include_dir_named scripts/

sensor:
  - platform: template
    sensors: !include_dir_named sensor/sensors/

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
