# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

adaptive_lighting:
  lights:
    - light.bedroom_lights
    - light.hallway_lights
    - light.kitchen_lights
    - light.living_room_lights

automation: !include_dir_list automations

camera:
  - name: bedroom_air_quality
    platform: generic
    still_image_url: >-
      https://anoblet.duckdns.org:3000/api/hassio_ingress/US8_r4L34UbOMiwbsNQft89HxmTVfKTRETZagNTfMPw/render/d-solo/XYXLRzqGk/my-dashboard?orgId=1&panelId=2&width=2048&height=256&tz=America%2FNew_York

homeassistant:
  external_url: https://anoblet.duckdns.org

http:
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

influxdb:
  host: 192.168.0.120
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.ceiling
      - light.table
      - light.dresser
  - platform: group
    name: Living Room Lights
    entities:
      - light.ceiling_2
  - platform: group
    name: Hallway Lights
    entities:
      - light.hallway_one
      - light.hallway_two
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_one
      - light.kitchen_two
      - light.kitchen_three
      - light.kitchen_four
      - light.kitchen_five

logger:
  default: info
  logs: !include ./logger.yaml

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

media_player: !include media_player.yaml

recorder:
  db_url: !secret db_url

sensor:
  - platform: template
    sensors: !include_dir_named sensor/sensors/

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

vesync:
  username: !secret vesync_username
  password: !secret vesync_password
