# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

adaptive_lighting: !include_dir_list adaptive_lighting/

automation: !include automations.yaml

homeassistant:
  external_url: https://anoblet.duckdns.org

http:

light: !include_dir_list light/

logger:
  default: info
  logs: !include ./logger.yaml

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

media_player: !include media_player.yaml

recorder:
  db_url: !secret db_url

sensor:
  - platform: template
    sensors: !include_dir_named sensor/sensors/

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

vesync:
  username: !secret vesync_username
  password: !secret vesync_password
