title: Overview
views:
  - !include lovelace/views/view-home.yaml
  - !include lovelace/views/view-lights.yaml
  - !include lovelace/views/view-remotes.yaml
  - !include lovelace/views/view-fans.yaml
  - !include lovelace/views/view-network.yaml
