title: Overview
views:
  - !include lovelace/views/view-home.yaml
  - !include lovelace/views/view-lights.yaml
  - !include lovelace/views/view-remotes.yaml
  - !include lovelace/views/view-fans.yaml
  - !include lovelace/views/view-network.yaml
  - !include lovelace/views/view-weather.yaml
apexcharts_card_templates:
  default_chart:
    apex_config:
      chart:
        height: 256px
    # layout: minimal
    graph_span: 24h
    # span:
    # start: day
    # offset: -1d
    all_series_config:
      group_by:
        func: avg
        duration: 15m
      stroke_width: 2
      # type: column
  air_quality:
    apex_config:
      yaxis:
        min: 0
        max: 100
    config_templates: default_chart
    all_series_config:
      curve: stepline
      fill_raw: last
      group_by:
        func: min

