path: storage-room-configuration
subview: true
title: Configuration
type: sections
sections:
  - type: grid
    title: Adaptive Lighting Modes
    cards:
      - type: entities
        entities:
          - entity: switch.adaptive_lighting_storage_room
            name: Adaptive Lighting
          - entity: switch.adaptive_lighting_adapt_brightness_storage_room
            name: Adaptive Lighting Brightness
          - entity: switch.adaptive_lighting_adapt_color_storage_room
            name: Adaptive Lighting Color
          - entity: switch.adaptive_lighting_sleep_mode_storage_room
            name: Adaptive Lighting Sleep Mode
