living_room_thermostat_default:
  input_number:
    living_room_thermostat_default:
      max: 100
      min: 0
      mode: box
      name: Living Room Thermostat Default
      step: 1
      unit_of_measurement: °F
