substitutions:
  name: esp32-s3-box-3-0588b0
  friendly_name: ESP32 S3 Box 3 0588b0
packages:
  esphome.voice-assistant: github://esphome/wake-word-voice-assistants/esp32-s3-box-3/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 4MbGII6jbFZXd8GJjazCQ/xkjuPGxBOYE/X0x3cqQFs=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
