path: kitchen-configuration
subview: true
title: Configuration
type: sections
sections:
  - type: grid
    title: Occupancy
    cards:
      - type: entities
        entities:
          - entity: input_boolean.kitchen_ld2410c
            name: Presence Detection
  - type: grid
    title: Lighting Automation
    cards:
      - type: entities
        entities:
          - entity: input_boolean.kitchen_motion
            name: Motion Lighting
          - entity: input_number.kitchen_motion_cooldown
            name: Motion Cooldown
          - entity: input_number.kitchen_illuminance_minimum
            name: Illuminance Minimum
          - entity: input_number.kitchen_light_transition_on
            name: Light Transition On
          - entity: input_number.kitchen_light_transition_off
            name: Light Transition Off
  - type: grid
    title: Climate Control
    cards:
      - type: entities
        entities:
          - entity: switch.kitchen_air_conditioner_virtual
            name: Air Conditioner
  - type: grid
    title: Adaptive Lighting Modes
    cards:
      - type: entities
        entities:
          - entity: switch.adaptive_lighting_kitchen
            name: Adaptive Lighting
          - entity: switch.adaptive_lighting_adapt_brightness_kitchen
            name: Adaptive Lighting Brightness
          - entity: switch.adaptive_lighting_adapt_color_kitchen
            name: Adaptive Lighting Color
          - entity: switch.adaptive_lighting_sleep_mode_kitchen
            name: Adaptive Lighting Sleep Mode
