api:
  encryption:
    key: !secret api_encryption_key
captive_portal:
esphome:
  friendly_name: ${esphome_friendly_name}
  name: ${esphome_name}
  name_add_mac_suffix: false
logger:
ota:
  - platform: esphome
    password: !secret ota_password
packages:
  wifi: !include wifi.yaml
