living_room_thermostat_heat_default:
  automation:
    - alias: 'Living Room - Thermostat - Heat - Default Reset'
      id: living_room_thermostat_heat_default_reset
      trigger:
        - platform: time_pattern
          hours: '*'
          minutes: '0'
          seconds: '0'
        # Trigger when bedroom presence is off for 15 minutes
        - platform: state
          entity_id: binary_sensor.living_room_ld2410c_presence
          to: 'off'
          for:
            minutes: 15
      action:
        - service: climate.set_temperature
          target:
            entity_id: climate.living_room_thermostat_heat
          data:
            temperature: "{{ states('input_number.living_room_thermostat_heat_default') | float(70) }}"
  input_number:
    living_room_thermostat_heat_default:
      name: Living Room Thermostat Heat Default
      min: 0
      max: 100
      mode: box
      step: 1
      unit_of_measurement: '°F'
