substitutions:
  friendly_name: "Athom Smart Plug"
  name: athom-smart-plug
packages:
  athom.smart-plug: github://athom-tech/athom-configs/athom-smart-plug.yaml
esphome:
  name_add_mac_suffix: false
# time:
#   - platform: sntp
#     id: my_time
wifi:
  # manual_ip:
  #   static_ip: 192.168.0.215
  #   gateway: 192.168.0.1
  #   subnet: 255.255.255.0
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
