substitutions:
  friendly_name: "Bedroom Two Air Conditioner"
  esphome_name: bedroom-two-air-conditioner
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
  common: !include packages/common.yaml
