substitutions:
  cover_name: "Bedroom Blind Two"
  device_id: "bedroom_blind_two"
  esphome_friendly_name: Bedroom Blind Two
  esphome_name: "bedroom-blind-two"
packages:
  blinds: !include packages/blinds_reversed.yaml
