packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
  common: !include packages/common.yaml
substitutions:
  esphome_name: bedroom-heater
  friendly_name: "Bedroom Heater"
wifi:
  manual_ip:
    static_ip: 192.168.0.225
    gateway: 192.168.0.1
    subnet: 255.255.255.0
