packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
  common: !include packages/common.yaml
substitutions:
  esphome_name: bedroom-heater
  friendly_name: "Bedroom Heater"
