bme680_bsec:
  address: 0x77
esp8266:
  board: nodemcuv2
i2c:
  scan: false
  scl: 5
  sda: 4
packages:
  common: !include packages/common.yaml
sensor:
  - platform: bme680_bsec
    temperature:
      name: "Bedroom BME680 Temperature"
      filters:
        - median
    pressure:
      name: "Bedroom BME680 Pressure"
      filters:
        - median
    humidity:
      name: "Bedroom BME680 Humidity"
      filters:
        - median
    gas_resistance:
      name: "Bedroom BME680 Gas Resistance"
      filters:
        - median
    iaq:
      name: "Bedroom BME680 IAQ"
      filters:
        - median
    iaq_accuracy:
      name: "Bedroom BME680 Numeric IAQ Accuracy"
    co2_equivalent:
      name: "Bedroom BME680 CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      name: "Bedroom BME680 Breath VOC Equivalent"
      filters:
        - median
substitutions:
  esphome_name: bedroom-bme680
text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "Bedroom BME680 IAQ Accuracy"
