substitutions:
  friendly_name: "Bedroom Three Air Conditioner"
  name: bedroom-three-air-conditioner
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
wifi:
  manual_ip:
    static_ip: 192.168.0.238
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  ssid: !secret wifi_ssid
  password: !secret wifi_password
