esp8266:
  board: nodemcuv2
i2c:
  scan: false
  scl: 5
  sda: 4
logger:
ota:
  password: !secret ota_password
packages:
  common: !include packages/common.yaml
sensor:
  - address: 0x61
    co2:
      name: "Bedroom SCD30 Carbon Dioxide"
    humidity:
      name: "Bedroom SCD30 Humidity"
    id: scd30_id
    platform: scd30
    temperature:
      name: "Bedroom SCD30 Temperature"
    update_interval: 15s
substitutions:
  esphome_name: bedroom-scd30
