esp8266:
  board: nodemcuv2
i2c:
  scan: false
  scl: 5
  sda: 4
packages:
  common: !include packages/common.yaml
sensor:
  - address: 0x76
    humidity:
      name: Bedroom BME280 Humidity
    platform: bme280_i2c
    pressure:
      name: Bedroom BME280 Pressure
    temperature:
      name: Bedroom BME280 Temperature
substitutions:
  esphome_name: bedroom-bme280
