esp32:
  board: esp32dev
ld2410:
packages:
  common: !include packages/common.yaml
binary_sensor:
  - platform: ld2410
    has_target:
      name: Bedroom LD2410C Presence
    has_moving_target:
      name: Bedroom LD2410C Moving Target
    has_still_target:
      name: Bedroom LD2410C Still Target
    out_pin_presence_status:
      name: Bedroom LD2410C out pin presence status
button:
  - platform: ld2410
    factory_reset:
      name: Bedroom LD2410C Factory Reset Radar
    restart:
      name: Bedroom LD2410C Restart Radar
logger:
  baud_rate: 0
number:
  - platform: ld2410
    timeout:
      name: Bedroom LD2410C Radar Timeout
    max_move_distance_gate:
      name: Bedroom LD2410C Radar Max Move Distance
    max_still_distance_gate:
      name: Bedroom LD2410C Radar Max Still Distance
    g0:
      move_threshold:
        name: Bedroom LD2410C G0 move threshold
      still_threshold:
        name: Bedroom LD2410C G0 still threshold
    g1:
      move_threshold:
        name: Bedroom LD2410C G1 move threshold
      still_threshold:
        name: Bedroom LD2410C G1 still threshold
    g2:
      move_threshold:
        name: Bedroom LD2410C G2 move threshold
      still_threshold:
        name: Bedroom LD2410C G2 still threshold
    g3:
      move_threshold:
        name: Bedroom LD2410C G3 move threshold
      still_threshold:
        name: Bedroom LD2410C G3 still threshold
    g4:
      move_threshold:
        name: Bedroom LD2410C G4 move threshold
      still_threshold:
        name: Bedroom LD2410C G4 still threshold
    g5:
      move_threshold:
        name: Bedroom LD2410C G5 move threshold
      still_threshold:
        name: Bedroom LD2410C G5 still threshold
    g6:
      move_threshold:
        name: Bedroom LD2410C G6 move threshold
      still_threshold:
        name: Bedroom LD2410C G6 still threshold
    g7:
      move_threshold:
        name: Bedroom LD2410C G7 move threshold
      still_threshold:
        name: Bedroom LD2410C G7 still threshold
    g8:
      move_threshold:
        name: Bedroom LD2410C G8 move threshold
      still_threshold:
        name: Bedroom LD2410C G8 still threshold
sensor:
  - platform: ld2410
    moving_distance:
      name: Bedroom LD2410C Radar Moving Distance
      id: moving_distance
    still_distance:
      name: Bedroom LD2410C Radar Still Distance
      id: still_distance
    moving_energy:
      name: Bedroom LD2410C Radar Move Energy
    still_energy:
      name: Bedroom LD2410C Radar Still Energy
    detection_distance:
      name: Bedroom LD2410C Radar Detection Distance
      id: radar_detection_distance
    g0:
      move_energy:
        name: Bedroom LD2410C G0 move energy
      still_energy:
        name: Bedroom LD2410C G0 still energy
    g1:
      move_energy:
        name: Bedroom LD2410C G1 move energy
      still_energy:
        name: Bedroom LD2410C G1 still energy
    g2:
      move_energy:
        name: Bedroom LD2410C G2 move energy
      still_energy:
        name: Bedroom LD2410C G2 still energy
    g3:
      move_energy:
        name: Bedroom LD2410C G3 move energy
      still_energy:
        name: Bedroom LD2410C G3 still energy
    g4:
      move_energy:
        name: Bedroom LD2410C G4 move energy
      still_energy:
        name: Bedroom LD2410C G4 still energy
    g5:
      move_energy:
        name: Bedroom LD2410C G5 move energy
      still_energy:
        name: Bedroom LD2410C G5 still energy
    g6:
      move_energy:
        name: Bedroom LD2410C G6 move energy
      still_energy:
        name: Bedroom LD2410C G6 still energy
    g7:
      move_energy:
        name: Bedroom LD2410C G7 move energy
      still_energy:
        name: Bedroom LD2410C G7 still energy
    g8:
      move_energy:
        name: Bedroom LD2410C G8 move energy
      still_energy:
        name: Bedroom LD2410C G8 still energy
substitutions:
  esphome_name: bedroom-ld2410c
  friendly_name: Bedroom LD2410C
switch:
  - platform: ld2410
    bluetooth:
      name: Bedroom LD2410C Radar Control Bluetooth
      id: radar_bluetooth
    engineering_mode:
      name: Bedroom LD2410C Radar Engineering Mode
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
