api:
  encryption:
    key: !secret api_encryption_key
esphome:
  name: ${name}
  name_add_mac_suffix: false
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
substitutions:
  friendly_name: "Bedroom Air Conditioner"
  name: bedroom-air-conditioner
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
