api:
  # encryption:
  #   key: !secret api_encryption_key
captive_portal:
esphome:
  friendly_name: ${friendly_name}
  name: ${esphome_name}
  name_add_mac_suffix: false
logger:
ota:
  - platform: esphome
    password: !secret ota_password
substitutions:
  esphome_name: kitchen-air-fryer
  friendly_name: Kitchen Air Fryer
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
wifi:
  ap:
    password: !secret wifi_ap_password
    ssid: $esphome_name
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.116
    gateway: 192.168.1.1
    subnet: 255.255.255.0
