substitutions:
  friendly_name: "Kitchen Air Conditioner"
  name: kitchen-air-conditioner
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
api:
  encryption:
    key: !secret api_encryption_key
esphome:
  name: ${name}
  name_add_mac_suffix: false
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
