substitutions:
  friendly_name: "Kitchen Water Cooler"
  name: kitchen-water-cooler
packages:
  athom.smart-plug: github://athom-tech/athom-configs/athom-smart-plug.yaml
esphome:
  name_add_mac_suffix: false
wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
