substitutions:
  cover_name: "Living Room Blind One"
  device_id: "living_room_blind_one"
  esphome_friendly_name: Living Room Blind One
  esphome_name: "living-room-blind-one"
packages:
  blinds: !include packages/blinds.yaml
