substitutions:
  cover_name: "Living Room Blind Two"
  device_id: "living_room_blind_two"
  esphome_friendly_name: Living Room Blind Two
  esphome_name: "living-room-blind-two"
packages:
  blinds: !include packages/blinds.yaml
