substitutions:
  friendly_name: "Storage Room Printer"
  name: "storage-room-printer"
packages:
  athom.smart-plug: github://athom-tech/athom-configs/athom-smart-plug.yaml
esphome:
  name_add_mac_suffix: false
wifi:
  manual_ip:
    static_ip: 192.168.0.134
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  ssid: !secret wifi_ssid
  password: !secret wifi_password
